using System.IO;

namespace Kinetix.ClassGenerator.SchemaGenerator
{
    /// <summary>
    /// Générateur de PL-SQL.
    /// </summary>
    public class PostgreSchemaGenerator : AbstractSchemaGenerator
    {
        /// <summary>
        /// Séparateur de lots de commandes PL-SQL.
        /// </summary>
        protected override string BatchSeparator => ";";

        /// <summary>
        /// Indique si le moteur de BDD visé supporte "primary key clustered ()".
        /// </summary>
        protected override bool SupportsClusteredKey => false;

        /// <summary>
        /// Gère l'auto-incrémentation des clés primaires en ajoutant identity à la colonne.
        /// </summary>
        /// <param name="writerCrebas">Flux d'écriture création bases.</param>
        protected override void WriteIdentityColumn(StreamWriter writerCrebas)
        {
            writerCrebas.Write(" generated by default as identity");
        }
    }
}
